# Generated by Django 2.2.4 on 2019-12-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friend_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
