# Generated by Django 2.2.6 on 2019-11-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_sys', '0005_auto_20191116_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
