# Generated by Django 2.2.4 on 2019-12-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_sys', '0016_auto_20191205_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='vista',
            field=models.BooleanField(default=False),
        ),
    ]
