# Generated by Django 2.2.4 on 2019-12-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_sys', '0017_messages_vista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='vista',
            new_name='viewed',
        ),
    ]
